name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch upstream changes
        run: git fetch upstream
      
      - name: Merge upstream changes
        run: git merge upstream/main # Replace 'main' with the name of the branch you want to sync with
      
      - name: Push changes to fork
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
